### ISSUE TITLE
It took more than an hour to receive sent emails via Microsoft Exchange Web Services (EWS)

### ISSUE THREAD

**Issue by kupiqu** [KrissN/akonadi-ews#1]
It took more than an hour to receive sent emails via the Microsoft Exchange Web Services (EWS). This is related to the following comment:

[https://micreabog.wordpress.com/2016/05/01/akonadi-resource-for-microsoft-exchange-web-services-ews/#comment-5](https://micreabog.wordpress.com/2016/05/01/akonadi-resource-for-microsoft-exchange-web-services-ews/#comment-5)

The same issue occurred in two identical tests. Both tests had no body, neither attachments (but were identified by a distinct subject).

In contrast, the same typeof email arrived within a minute if sent through the SMTP server (which I use for now as a workaround).

Please let me know if you would like me to help doing further testing.

**Comment by KrissN** [comment]
Can you try this for me:

1. Open a terminal
2. Execute: `ps -u | grep akonadi_ews_resource`. This will show you the process running your Exchange resource. Note the resource identifier - it should be `akonadi_ews_resource_0`, but the number at the end may be greater if you have several of them.
3. Execute: `while [ $(killall akonadi_ews_resource) ]; do true; done`
4. You should see a popup telling that your Exchange resource is broken. No big deal.
5. Execute the resource process with some logging enabled: `QT_LOGGING_RULE=log_ews_resource_request.debug=true /usr/bin/akonadi_ews_resource --identifier akonadi_ews_resource_0`. Change the identifier at the end to match the one obtained in step 2. You can also pipe the log into a file (append `> /tmp/ews.log` to the above command)
6. Try to send your e-mail.
7. Observe the log. Ideally you should see something like this:

> log_ews_resource_request: Starting CreateItem request (1 items, parent )
> log_ews_resource_request: "Got CreateItem response - OK"
> log_ews_resource_request: Starting CreateItem request (1 items, parent INBOX)
> log_ews_resource_request: "Got CreateItem response - OK"
> mailCreateFinished

The first CreateItem request (with empty parent) performs the actual mail transfer to the SMTP server. The second one puts a copy of your mail in the sent items folder (in my case I have chosen all outgoing mail to be placed in the inbox).

Once complete you can continue using KMail without closing the terminal or you can restart Akonadi in order to put the Exchange resource process back into background by running `akonadictl restart`.

**Comment by kupiqu** [comment]
ps command didn't find my ews processes, so I did:

```
pgrep -a akonadi_ews
6081 /usr/bin/akonadi_ews_resource --identifier akonadi_ews_resource_0
6082 /usr/bin/akonadi_ewsmta_resource --identifier akonadi_ewsmta_resource_0
```

Should I only kill ews or ewsmta as well?

**Comment by kupiqu** [comment]
wait, I think step 3 would actually kill them both, going to try...

**Comment by kupiqu** [comment]
Actually it did not, and akonadi_ews_resource was automatically restarted

**Comment by kupiqu** [comment]
Mmm, I repeated the test as requested and this new test worked as it should, it arrived within a minute.

Not sure what changed from Yesterday... Could it be that the server was busy synchronizing emails and this interfered?

I'll do some more tests and let you know...

**Comment by KrissN** [comment]
> Not sure what changed from Yesterday... Could it be that the server was busy synchronizing emails and this interfered?

It is possible as the resource (as any other one out there) is internally synchronous and processes requests on a FIFO basis.

**Comment by kupiqu** [comment]
I restarted akonadi and tried again, and it continues working great. Most likely it was just that the server was busy.

I'm then closing the issue. 

Sorry for the noise.

**Comment by KrissN** [comment]
No problem :)
