### ISSUE TITLE
Calendar: Display attendees for events

### ISSUE THREAD

**Issue by klada** [KrissN/akonadi-ews#42]
Hi,

I have a feature request for this very promising piece of software: it would be very cool if the attendees and their response could be displayed for EWS events.

**Comment by KrissN** [comment]
This feature is more a generic KMail/KOrganizer feature as even without EWS it is easily able to determine who accepted or declined the event.

I agree though - a nice thing to have.

**Comment by klada** [comment]
Wait, I don't understand. Currently there are no attendees in my akonadi-ews calendar. The support for this is definitely there both in KOrganizer and in the EWS protocol itself.

So this is actually an issue with akonadi-ews, as it does not populate the attendees in the calendar. And in the code I do not find mappings for the attendee field/status.

What do you mean by _it is easily able to determine who accepted or declined the event_?

**Comment by KrissN** [comment]
At the moment the EWS resource is passing a vCard to Akonadi, which also contains all attendees of the event, so the attendees should be visible. If they're not, the problem is most likely in the calendar core somewhere.

As for attendee status, there are two ways to do it:

- Monitor the inbox for calendar event invitation replies and update the status for each of them (the offline method).
- Query the Exchange server (via EWS) as to the state of each attendee (online method).

At the moment it should be easily possible to support the "offline method", which I believe is also in use by Thunderbird/Lightning. Support for the "online method" can be added to the EWS resource, and it is on the TODO list.

**Comment by klada** [comment]
Thanks for the clarification. I think what I mean is the "online method". Each event from the EWS API should have `Organizer`, `RequiredAttendees` and `OptionalAttendees` fields (at least optionally). I think this does not anything to do with vCards (it could be translated into plain ICS, though).

I also found some references to these EWS attributes in `akonadi-ews/calendar/ewsfetchcalendardetailjob.cpp`, but right now they are commented out, so I think right now this is simply not implemented. That's why I think that this issue is still valid.

**Comment by KrissN** [comment]
They are commented out because the current calendar implementation is greatly simplified, which is the reason why it is read-only. The full implementation will use the EWS fields you mentioned to retrieve information about attendees and in this case it will also be possible to retrieve their state.

**Comment by KrissN** [comment]
Created KDE Phabricator task: https://phabricator.kde.org/T7177
